name: C/C++ CI

on:
  push:
    branches: [ alpha ]
  pull_request:
    branches: [ alpha ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make -C 3_Implementation/ all
