# This is a basic workflow to help you get started with Actions

name: Code Quality - Static Code - Cppcheck

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the alpha branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  cppcheck:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install cppcheck
      run: sudo apt -y install cppcheck
    - name: Run cppcheck
      run: cppcheck 3_Implementation
