# This is a basic workflow to help you get started with Actions

name: CodeQuality Dynamic Code Analysis Valgrind

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the alpha branch
  push:
    branches: [ alpha ]
  pull_request:
    branches: [ alpha ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: apt install dependency
      run: |
        sudo apt-get -y install valgrind
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
    - name: make test
      run: make -C 3_Implementation/ test
    - name: Valgrid
      run: valgrind ./3_Implementation/build/Test_Calendar.out